vim.api.nvim_command("hi clear")
vim.api.nvim_command("hi ALEErrorSign guifg=#ff5874 ctermfg=204 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi ALEWarningSign guifg=#FD9720 ctermfg=208 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi ALEInfoSign guifg=#addb67 ctermfg=149 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi Normal guifg=#ddd0f4 ctermfg=189 guibg=#211c2f ctermbg=234 gui=NONE cterm=NONE")
vim.api.nvim_command("hi LineNr guifg=#4f425e ctermfg=239 guibg=#211c2f ctermbg=234 gui=NONE cterm=NONE")
vim.api.nvim_command("hi CursorLine guifg=NONE ctermfg=NONE guibg=#343047 ctermbg=236 gui=bold cterm=bold")
vim.api.nvim_command("hi CursorLineNr guifg=#1aad16 ctermfg=34 guibg=#1a1926 ctermbg=234 gui=bold cterm=bold")
vim.api.nvim_command("hi ColorColumn guifg=NONE ctermfg=NONE guibg=#22202a ctermbg=235 gui=NONE cterm=NONE")
vim.api.nvim_command("hi Cursor guibg=#ddd0f4 ctermbg=189 gui=NONE cterm=NONE")
vim.api.nvim_command("hi CursorIM guifg=#ddd0f4 ctermfg=189 guibg=#5f7e97 ctermbg=66 gui=NONE cterm=NONE")
vim.api.nvim_command("hi CursorColumn guibg=#343047 ctermbg=236 gui=NONE cterm=NONE")
vim.api.nvim_command("hi Directory guifg=#82aaf0 ctermfg=111 gui=NONE cterm=NONE")
vim.api.nvim_command("hi DiffAdd guifg=#addb67 ctermfg=149 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi DiffChange guifg=#ecc48d ctermfg=222 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi DiffDelete guifg=#ff5874 ctermfg=204 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi DiffText guifg=#77d507 ctermfg=112 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi ErrorMsg guifg=#DC143C ctermfg=161 guibg=NONE ctermbg=NONE gui=bold cterm=bold")
vim.api.nvim_command("hi VertSplit guifg=#777087 ctermfg=243 gui=NONE cterm=NONE")
vim.api.nvim_command("hi Folded guifg=#777087 ctermfg=243 guibg=#141425 ctermbg=233 gui=NONE cterm=NONE")
vim.api.nvim_command("hi FoldColumn guifg=#333042 ctermfg=236 guibg=#141425 ctermbg=233 gui=NONE cterm=NONE")
vim.api.nvim_command("hi SignColumn guifg=NONE ctermfg=NONE guibg=#141425 ctermbg=233 gui=NONE cterm=NONE")
vim.api.nvim_command("hi IncSearch guifg=NONE ctermfg=NONE guibg=#282437 ctermbg=235 gui=bold,undercurl,italic cterm=bold,undercurl,italic guisp=#ecc48d")
vim.api.nvim_command("hi MatchParen guifg=#EE82EE ctermfg=213 guibg=NONE ctermbg=NONE gui=bold,undercurl cterm=bold,undercurl guisp=#E7C547")
vim.api.nvim_command("hi ModeMsg guifg=#77d507 ctermfg=112 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi MoreMsg guifg=#aab7cf ctermfg=146 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi NonText guifg=#4f425e ctermfg=239 gui=NONE cterm=NONE")
vim.api.nvim_command("hi PMenu guifg=#888ca9 ctermfg=103 guibg=#141425 ctermbg=233 gui=NONE cterm=NONE")
vim.api.nvim_command("hi PMenuSel guifg=#e7d3fb ctermfg=189 guibg=#443a54 ctermbg=238 gui=bold,italic cterm=bold,italic")
vim.api.nvim_command("hi PmenuSbar guifg=NONE ctermfg=NONE guibg=#4f425e ctermbg=239 gui=NONE cterm=NONE")
vim.api.nvim_command("hi PmenuThumb guifg=NONE ctermfg=NONE guibg=#aab7cf ctermbg=146 gui=NONE cterm=NONE")
vim.api.nvim_command("hi Question guifg=#6690c4 ctermfg=68 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi Search guifg=NONE ctermfg=NONE guibg=#585010 ctermbg=58 gui=bold,undercurl,italic cterm=bold,undercurl,italic guisp=#B376B3")
vim.api.nvim_command("hi SpecialKey guifg=#ecc48d ctermfg=222 gui=NONE cterm=NONE")
vim.api.nvim_command("hi SpellBad guifg=#9c3f37 ctermfg=131 guibg=NONE ctermbg=NONE gui=undercurl cterm=undercurl guisp=#9c3f37")
vim.api.nvim_command("hi SpellCap guifg=#5ca7e4 ctermfg=74 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi SpellRare guifg=#99c794 ctermfg=114 guibg=NONE ctermbg=NONE gui=undercurl cterm=undercurl guisp=#addb67")
vim.api.nvim_command("hi StatusLine guifg=#ddd0f4 ctermfg=189 guibg=#1a1926 ctermbg=234 gui=NONE cterm=NONE")
vim.api.nvim_command("hi StatusLineNC guifg=#777087 ctermfg=243 guibg=#1a1926 ctermbg=234 gui=NONE cterm=NONE")
vim.api.nvim_command("hi TabLine guifg=#7BA1D0 ctermfg=110 guibg=#211c2f ctermbg=234 gui=NONE cterm=NONE")
vim.api.nvim_command("hi TabLineFill guifg=#333042 ctermfg=236 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi TabLineSel guifg=#10aef8 ctermfg=39 guibg=NONE ctermbg=NONE gui=underline cterm=underline")
vim.api.nvim_command("hi Title guifg=#82aaf0 ctermfg=111 gui=bold cterm=bold")
vim.api.nvim_command("hi Visual guibg=#4f4764 ctermbg=239 gui=NONE cterm=NONE")
vim.api.nvim_command("hi VisualNOS guifg=#637077 ctermfg=243 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi WarningMsg guifg=#ec5f67 ctermfg=203 gui=undercurl cterm=undercurl guisp=#5f0000")
vim.api.nvim_command("hi WildMenu guifg=#777087 ctermfg=243 guibg=#211c2f ctermbg=234 gui=NONE cterm=NONE")
vim.api.nvim_command("hi EndOfBuffer guifg=#4f425e ctermfg=239 guibg=#1a1926 ctermbg=234 gui=NONE cterm=NONE")
vim.api.nvim_command("hi Comment guifg=#76715E ctermfg=243 gui=italic cterm=italic")
vim.api.nvim_command("hi Constant guifg=#1aad16 ctermfg=34 gui=NONE cterm=NONE")
vim.api.nvim_command("hi String guifg=#2ba245 ctermfg=35 gui=NONE cterm=NONE")
vim.api.nvim_command("hi Character guifg=#be9af7 ctermfg=141 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi Boolean guifg=#EE82EE ctermfg=213 gui=italic cterm=italic")
vim.api.nvim_command("hi Number guifg=#ff7f50 ctermfg=209 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi Float guifg=#ec5f67 ctermfg=203 gui=bold cterm=bold")
vim.api.nvim_command("hi Identifier guifg=#A6E22D ctermfg=148 gui=NONE cterm=NONE")
vim.api.nvim_command("hi Function guifg=#10aef8 ctermfg=39 gui=bold cterm=bold")
vim.api.nvim_command("hi Statement guifg=#F92772 ctermfg=197 gui=bold cterm=bold")
vim.api.nvim_command("hi Conditional guifg=#99c794 ctermfg=114 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi Repeat guifg=#FF435B ctermfg=203 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi Label guifg=#5f875f ctermfg=65 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi Operator guifg=#A1EFE4 ctermfg=158 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi Keyword guifg=#B77EE0 ctermfg=140 gui=bold cterm=bold")
vim.api.nvim_command("hi Exception guifg=#e55285 ctermfg=168 gui=NONE cterm=NONE")
vim.api.nvim_command("hi PreProc guifg=#EE82EE ctermfg=213 gui=NONE cterm=NONE")
vim.api.nvim_command("hi Include guifg=#ae81ef ctermfg=141 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi Define guifg=#88dfe9 ctermfg=116 gui=italic cterm=italic")
vim.api.nvim_command("hi Macro guifg=#C33C4A ctermfg=131 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi PreCondit guifg=#d7ffaf ctermfg=193 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi Type guifg=#67d5b5 ctermfg=79 gui=bold cterm=bold")
vim.api.nvim_command("hi StorageClass guifg=#01d5f1 ctermfg=45 gui=NONE cterm=NONE")
vim.api.nvim_command("hi Structure guifg=#ae81ef ctermfg=141 gui=bold,italic cterm=bold,italic")
vim.api.nvim_command("hi Typedef guifg=#66d9ef ctermfg=81 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi Special guifg=#FF6347 ctermfg=203 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi SpecialChar guifg=#F92772 ctermfg=197 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi Tag guifg=#FF5D71 ctermfg=203 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi htmlTag guifg=#637077 ctermfg=243 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi link htmlEndTag htmlTag")
vim.api.nvim_command("hi Delimiter guifg=#a8dff9 ctermfg=153 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi SpecialComment guifg=#637077 ctermfg=243 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi Debug guifg=#6189bb ctermfg=67 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi Underlined guifg=#67d5b5 ctermfg=79 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi Ignore guifg=#4f425e ctermfg=239 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi Error guifg=#DC143C ctermfg=161 guibg=NONE ctermbg=NONE gui=bold,undercurl cterm=bold,undercurl guisp=#e7dc8c")
vim.api.nvim_command("hi Todo guifg=#e73c50 ctermfg=167 guibg=NONE ctermbg=NONE gui=bold,italic cterm=bold,italic")
vim.api.nvim_command("hi BuffetCurrentBuffer guifg=#443a54 ctermfg=238 guibg=#3649dc ctermbg=62 gui=NONE cterm=NONE")
vim.api.nvim_command("hi BuffetActiveBuffer guifg=#282437 ctermfg=235 guibg=#3649dc ctermbg=62 gui=NONE cterm=NONE")
vim.api.nvim_command("hi BuffetBuffer guibg=#b4b0e0 ctermbg=146 gui=NONE cterm=NONE")
vim.api.nvim_command("hi BuffetModCurrentBuffer guifg=#443a54 ctermfg=238 guibg=#3649dc ctermbg=62 gui=NONE cterm=NONE")
vim.api.nvim_command("hi BuffetModActiveBuffer guifg=#343047 ctermfg=236 guibg=#3649dc ctermbg=62 gui=NONE cterm=NONE")
vim.api.nvim_command("hi BuffetModBuffer guifg=#343047 ctermfg=236 guibg=#3649dc ctermbg=62 gui=NONE cterm=NONE")
vim.api.nvim_command("hi BuffetTrunc guibg=#82aaf0 ctermbg=111 gui=NONE cterm=NONE")
vim.api.nvim_command("hi BuffetTab guibg=#addb67 ctermbg=149 gui=NONE cterm=NONE")
vim.api.nvim_command("hi ClapPreview guibg=#282437 ctermbg=235 gui=NONE cterm=NONE")
vim.api.nvim_command("hi ClapMatches guifg=#C33C4A ctermfg=131 guibg=#443a54 ctermbg=238 gui=bold,undercurl,reverse cterm=bold,undercurl,reverse guisp=#f05874")
vim.api.nvim_command("hi ClapDisplay guifg=#aab7cf ctermfg=146 guibg=#211c2f ctermbg=234 gui=bold,undercurl cterm=bold,undercurl guisp=#f05874")
vim.api.nvim_command("hi CocErrorSign guifg=#f05874 ctermfg=204 gui=NONE cterm=NONE")
vim.api.nvim_command("hi CocWarningSign guifg=#fbfcbf ctermfg=229 gui=NONE cterm=NONE")
vim.api.nvim_command("hi CocHintSign guifg=#5ca7e4 ctermfg=74 gui=NONE cterm=NONE")
vim.api.nvim_command("hi CocInfoSign guifg=#fbec9f ctermfg=229 gui=NONE cterm=NONE")
vim.api.nvim_command("hi CocLine gui=undercurl cterm=undercurl guisp=#FD9720")
vim.api.nvim_command("hi CocUnderline gui=undercurl cterm=undercurl guisp=#FD9720")
vim.api.nvim_command("hi CocErrorline gui=undercurl cterm=undercurl guisp=#DC143C")
vim.api.nvim_command("hi cPreCondit guifg=#4cc7e4 ctermfg=80 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi cDefine guifg=#3649dc ctermfg=62 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi cStructure guifg=#6690c4 ctermfg=68 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi cStorageClass guifg=#50B4DC ctermfg=74 guibg=NONE ctermbg=NONE gui=bold cterm=bold")
vim.api.nvim_command("hi cCustomClass guifg=#b4b0e0 ctermfg=146 guibg=NONE ctermbg=NONE gui=bold cterm=bold")
vim.api.nvim_command("hi cCustomMemVar guifg=#50c878 ctermfg=78 guibg=NONE ctermbg=NONE gui=bold cterm=bold")
vim.api.nvim_command("hi cCustom guifg=#addb67 ctermfg=149 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi cType guifg=#3649dc ctermfg=62 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi cCustomParen guifg=#FD9720 ctermfg=208 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi cConditional guifg=#ecc48d ctermfg=222 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi cCustomFunc guifg=#10aef8 ctermfg=39 guibg=NONE ctermbg=NONE gui=bold cterm=bold")
vim.api.nvim_command("hi cStatement guifg=#F92772 ctermfg=197 guibg=NONE ctermbg=NONE gui=bold cterm=bold")
vim.api.nvim_command("hi cppSTLnamespace guifg=#6690c4 ctermfg=68 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi cppAccess guifg=#A1EFE4 ctermfg=158 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi cAnsiFunction guifg=#DDCFBF ctermfg=187 guibg=NONE ctermbg=NONE gui=bold cterm=bold")
vim.api.nvim_command("hi cRepeat guifg=#ecc48d ctermfg=222 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi cSpecial guifg=#333042 ctermfg=236 guibg=NONE ctermbg=NONE gui=bold cterm=bold")
vim.api.nvim_command("hi cssVendor guifg=#7fdbca ctermfg=116 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi cssTagName guifg=#7fdbca ctermfg=116 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi cssAttrComma guifg=#dacfb4 ctermfg=187 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi cssBackgroundProp guifg=#4cc7e4 ctermfg=80 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi cssBorderProp guifg=#4cc7e4 ctermfg=80 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi cssBoxProp guifg=#5ca7e4 ctermfg=74 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi cssDimensionProp guifg=#5ca7e4 ctermfg=74 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi cssFontProp guifg=#4cc7e4 ctermfg=80 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi cssPositioningProp guifg=#5ca7e4 ctermfg=74 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi cssTextProp guifg=#4cc7e4 ctermfg=80 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi cssValueLength guifg=#dacfb4 ctermfg=187 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi cssValueInteger guifg=#dacfb4 ctermfg=187 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi cssValueNumber guifg=#dacfb4 ctermfg=187 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi cssIdentifier guifg=#7fdbca ctermfg=116 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi cssIncludeKeyword guifg=#fbec9f ctermfg=229 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi cssImportant guifg=#f05874 ctermfg=204 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi cssClassName guifg=#9dd067 ctermfg=149 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi cssClassNameDot guifg=#dacfb4 ctermfg=187 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi cssProp guifg=#4cc7e4 ctermfg=80 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi cssAttr guifg=#dacfb4 ctermfg=187 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi cssUnitDecorators guifg=#dacfb4 ctermfg=187 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi cssNoise guifg=#f05874 ctermfg=204 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi diffRemoved guifg=#f05874 ctermfg=204 guibg=NONE ctermbg=NONE gui=bold cterm=bold")
vim.api.nvim_command("hi diffChanged guifg=#4cc7e4 ctermfg=80 guibg=NONE ctermbg=NONE gui=bold cterm=bold")
vim.api.nvim_command("hi diffAdded guifg=#9dd067 ctermfg=149 guibg=NONE ctermbg=NONE gui=bold cterm=bold")
vim.api.nvim_command("hi diffLine guifg=#fbed7d ctermfg=228 guibg=NONE ctermbg=NONE gui=bold cterm=bold")
vim.api.nvim_command("hi diffSubname guifg=#7fdbca ctermfg=116 guibg=NONE ctermbg=NONE gui=bold cterm=bold")
vim.api.nvim_command("hi diffComment guifg=#5f7e97 ctermfg=66 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi elmDelimiter guifg=#dacfb4 ctermfg=187 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi elmOperator guifg=#f05874 ctermfg=204 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi FugitiveblameHash guifg=#4cc7e4 ctermfg=80 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi FugitiveblameUncommitted guifg=#f05874 ctermfg=204 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi FugitiveblameTime guifg=#9dd067 ctermfg=149 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi FugitiveblameNotCommittedYet guifg=#fbec9f ctermfg=229 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi fzf1 guifg=#ecc48d ctermfg=222 guibg=#282437 ctermbg=235 gui=NONE cterm=NONE")
vim.api.nvim_command("hi fzf2 guifg=#FD9720 ctermfg=208 guibg=#282437 ctermbg=235 gui=NONE cterm=NONE")
vim.api.nvim_command("hi fzf3 guifg=#DC143C ctermfg=161 guibg=#282437 ctermbg=235 gui=NONE cterm=NONE")
vim.api.nvim_command("hi gitcommitBranch guifg=#5ca7e4 ctermfg=74 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi gitcommitDiscardedType guifg=#ec5f67 ctermfg=203 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi gitcommitSelectedType guifg=#7fdbca ctermfg=116 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi gitcommitHeader guifg=#4cc7e4 ctermfg=80 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi gitcommitUntrackedFile guifg=#fbec9f ctermfg=229 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi gitcommitDiscardedFile guifg=#f05874 ctermfg=204 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi gitcommitSelectedFile guifg=#9dd067 ctermfg=149 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi goBuiltins guifg=#01d5f1 ctermfg=45 guibg=NONE ctermbg=NONE gui=bold,italic cterm=bold,italic")
vim.api.nvim_command("hi goConditional guifg=#EE82EE ctermfg=213 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi goDeclType guifg=#9e71cf ctermfg=134 guibg=NONE ctermbg=NONE gui=bold cterm=bold")
vim.api.nvim_command("hi goDirective guifg=#CD5C5C ctermfg=167 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi goFloats guifg=#be9af7 ctermfg=141 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi goFunction guifg=#88dfe9 ctermfg=116 gui=bold cterm=bold")
vim.api.nvim_command("hi goFunctionCall guifg=#0fb9e0 ctermfg=38 gui=bold cterm=bold")
vim.api.nvim_command("hi goFunctionReturn guifg=#ae81ef ctermfg=141 gui=NONE cterm=NONE")
vim.api.nvim_command("hi goImport guifg=#A1EFE4 ctermfg=158 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi goLabel guifg=#FD9720 ctermfg=208 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi goMethod guifg=#10aef8 ctermfg=39 gui=bold cterm=bold")
vim.api.nvim_command("hi goMethodCall guifg=#66d9ef ctermfg=81 gui=bold cterm=bold")
vim.api.nvim_command("hi goPackage guifg=#EE82EE ctermfg=213 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi goRepeat guifg=#ffce51 ctermfg=221 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi goSignedInts guifg=#50c878 ctermfg=78 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi goStruct guifg=#ff7f50 ctermfg=209 gui=bold cterm=bold")
vim.api.nvim_command("hi goStructDef guifg=#87ceeb ctermfg=116 gui=bold cterm=bold")
vim.api.nvim_command("hi goUnsignedInts guifg=#be9af7 ctermfg=141 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi goParamName guifg=#fbec9f ctermfg=229 gui=NONE cterm=NONE")
vim.api.nvim_command("hi goParamType guifg=#E7C547 ctermfg=185 gui=NONE cterm=NONE")
vim.api.nvim_command("hi goParen guifg=#fbed7d ctermfg=228 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi goDeclaration guifg=#D57CD5 ctermfg=176 gui=bold cterm=bold")
vim.api.nvim_command("hi goSameId guifg=NONE ctermfg=NONE guibg=#343047 ctermbg=236 gui=bold,undercurl,italic cterm=bold,undercurl,italic")
vim.api.nvim_command("hi goPredefinedIdentifiers guifg=#CD5C5C ctermfg=167 gui=italic cterm=italic")
vim.api.nvim_command("hi goVar guifg=#ff7273 ctermfg=203 gui=bold cterm=bold")
vim.api.nvim_command("hi goType guifg=#ffce51 ctermfg=221 gui=bold cterm=bold")
vim.api.nvim_command("hi goTypeDecl guifg=#E6DB74 ctermfg=186 gui=bold cterm=bold")
vim.api.nvim_command("hi goTypeName guifg=#FF5D71 ctermfg=203 gui=bold cterm=bold")
vim.api.nvim_command("hi helpHyperTextEntry guifg=#9dd067 ctermfg=149 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi helpHeadline guifg=#5ca7e4 ctermfg=74 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi helpSectionDelim guifg=#222222 ctermfg=235 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi helpNote guifg=#f05874 ctermfg=204 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi jsStorageClass guifg=#4cc7e4 ctermfg=80 gui=NONE cterm=NONE")
vim.api.nvim_command("hi jsOperator guifg=#be9af7 ctermfg=141 gui=NONE cterm=NONE")
vim.api.nvim_command("hi jsArrowFunction guifg=#7fdbca ctermfg=116 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi jsGlobalNodeObjects guifg=#4cc7e4 ctermfg=80 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi jsString guifg=#1aad16 ctermfg=34 gui=italic cterm=italic")
vim.api.nvim_command("hi jsComment guifg=#637077 ctermfg=243 gui=italic cterm=italic")
vim.api.nvim_command("hi jsFuncCall guifg=#54CED6 ctermfg=80 gui=NONE cterm=NONE")
vim.api.nvim_command("hi jsNumber guifg=#fbec9f ctermfg=229 gui=NONE cterm=NONE")
vim.api.nvim_command("hi jsSpecial guifg=#fbec9f ctermfg=229 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi jsObjectProp guifg=#2ba245 ctermfg=35 gui=NONE cterm=NONE")
vim.api.nvim_command("hi jsOperatorKeyword guifg=#1aad16 ctermfg=34 gui=NONE cterm=NONE")
vim.api.nvim_command("hi jsBooleanFalse guifg=#ff5874 ctermfg=204 gui=NONE cterm=NONE")
vim.api.nvim_command("hi jsBooleanTrue guifg=#ff5874 ctermfg=204 gui=NONE cterm=NONE")
vim.api.nvim_command("hi jsRegexpString guifg=#5ca7e4 ctermfg=74 gui=NONE cterm=NONE")
vim.api.nvim_command("hi jsConditional guifg=#be9af7 ctermfg=141 gui=NONE cterm=NONE")
vim.api.nvim_command("hi jsFunction guifg=#10aef8 ctermfg=39 gui=NONE cterm=NONE")
vim.api.nvim_command("hi jsFunctionCall guifg=#9eeb61 ctermfg=149 gui=NONE cterm=NONE")
vim.api.nvim_command("hi jsFuncBlock guifg=#10aef8 ctermfg=39 gui=NONE cterm=NONE")
vim.api.nvim_command("hi jsReturn guifg=#be9af7 ctermfg=141 gui=NONE cterm=NONE")
vim.api.nvim_command("hi jsFuncName guifg=#2782d4 ctermfg=32 gui=NONE cterm=NONE")
vim.api.nvim_command("hi link jsParensError jsFuncParens")
vim.api.nvim_command("hi jsClassDefinition guifg=#ecc48d ctermfg=222 gui=NONE cterm=NONE")
vim.api.nvim_command("hi jsImport guifg=#5ca7e4 ctermfg=74 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi jsFrom guifg=#5ca7e4 ctermfg=74 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi jsModuleAs guifg=#ae81ef ctermfg=141 gui=italic cterm=italic")
vim.api.nvim_command("hi jsExport guifg=#5ca7e4 ctermfg=74 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi jsExportDefault guifg=#9dd067 ctermfg=149 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi jsExtendsKeyword guifg=#B376B3 ctermfg=139 gui=italic cterm=italic")
vim.api.nvim_command("hi javaScriptReserved guifg=#82aaf0 ctermfg=111 gui=NONE cterm=NONE")
vim.api.nvim_command("hi javaScriptConditional guifg=#be9af7 ctermfg=141 gui=NONE cterm=NONE")
vim.api.nvim_command("hi javaScriptStringS guifg=#ecc48d ctermfg=222 gui=NONE cterm=NONE")
vim.api.nvim_command("hi javaScriptBoolean guifg=#ff5874 ctermfg=204 gui=NONE cterm=NONE")
vim.api.nvim_command("hi javaScriptBraces guifg=#e7d3fb ctermfg=189 gui=NONE cterm=NONE")
vim.api.nvim_command("hi javaScriptLineComment guifg=#637077 ctermfg=243 gui=italic cterm=italic")
vim.api.nvim_command("hi javaScriptSpecial guifg=#fbec9f ctermfg=229 gui=NONE cterm=NONE")
vim.api.nvim_command("hi javaScriptFunction guifg=#50B4DC ctermfg=74 gui=NONE cterm=NONE")
vim.api.nvim_command("hi javaScriptStatement guifg=#be9af7 ctermfg=141 gui=NONE cterm=NONE")
vim.api.nvim_command("hi javaScriptException guifg=#D93234 ctermfg=167 gui=NONE cterm=NONE")
vim.api.nvim_command("hi jsonEscape guifg=#5ca7e4 ctermfg=74 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi jsonNumber guifg=#fbec9f ctermfg=229 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi jsonBraces guifg=#dacfb4 ctermfg=187 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi jsonNull guifg=#fbec9f ctermfg=229 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi jsonBoolean guifg=#fbec9f ctermfg=229 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi jsonKeywordMatch guifg=#f05874 ctermfg=204 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi jsonQuote guifg=#dacfb4 ctermfg=187 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi jsonNoise guifg=#f05874 ctermfg=204 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi LspDiagnosticsError guifg=#9c3f37 ctermfg=131 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi LspDiagnosticsErrorSign guifg=#D93234 ctermfg=167 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi LspDiagnosticsErrorFloating guifg=#9c3f37 ctermfg=131 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi LspDiagnosticsWarning guifg=#f4d554 ctermfg=221 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi LspDiagnosticsWarningSign guifg=#DBC08A ctermfg=180 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi LspDiagnosticsWarningFloating guifg=#DBC08A ctermfg=180 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi LspDiagnosticsInformation guifg=#7AA6DA ctermfg=110 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi LspDiagnosticsInformationSign guifg=#7AA6DA ctermfg=110 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi LspDiagnosticsInformationFloating guifg=#7AA6DA ctermfg=110 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi LspDiagnosticsHint guifg=#7AA6DA ctermfg=110 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi LspDiagnosticsHintSign guifg=#99c794 ctermfg=114 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi LspDiagnosticsHintFloating guifg=#1ABC9C ctermfg=37 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi LspReferenceText guibg=#4f4764 ctermbg=239 gui=bold,undercurl cterm=bold,undercurl guisp=#FD9720")
vim.api.nvim_command("hi LspReferenceRead guifg=#1aad16 ctermfg=34 gui=bold,undercurl cterm=bold,undercurl guisp=#FD9720")
vim.api.nvim_command("hi LspReferenceWrite guifg=#1aad16 ctermfg=34 gui=bold,undercurl cterm=bold,undercurl guisp=#FD9720")
vim.api.nvim_command("hi markdownH1 guifg=#4cc7e4 ctermfg=80 guibg=NONE ctermbg=NONE gui=bold cterm=bold")
vim.api.nvim_command("hi markdownHeadingRule guifg=#f05874 ctermfg=204 guibg=NONE ctermbg=NONE gui=bold cterm=bold")
vim.api.nvim_command("hi markdownHeadingDelimiter guifg=#f05874 ctermfg=204 guibg=NONE ctermbg=NONE gui=bold cterm=bold")
vim.api.nvim_command("hi markdownListMarker guifg=#fbec9f ctermfg=229 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi markdownBlockquote guifg=#fbec9f ctermfg=229 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi markdownRule guifg=#9dd067 ctermfg=149 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi markdownLinkText guifg=#9dd067 ctermfg=149 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi markdownLinkTextDelimiter guifg=#4cc7e4 ctermfg=80 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi markdownLinkDelimiter guifg=#4cc7e4 ctermfg=80 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi markdownIdDeclaration guifg=#7fdbca ctermfg=116 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi markdownAutomaticLink guifg=#5ca7e4 ctermfg=74 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi markdownUrl guifg=#5ca7e4 ctermfg=74 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi markdownUrlTitle guifg=#fbfcbf ctermfg=229 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi markdownUrlDelimiter guifg=#fbec9f ctermfg=229 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi markdownUrlTitleDelimiter guifg=#fbed7d ctermfg=228 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi markdownCodeDelimiter guifg=#5ca7e4 ctermfg=74 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi markdownCode guifg=#fbfcbf ctermfg=229 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi markdownEscape guifg=#5ca7e4 ctermfg=74 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi markdownError guifg=#f05874 ctermfg=204 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi NERDTreeHelp guifg=#dacfb4 ctermfg=187 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi NERDTreeHelpKey guifg=#9dd067 ctermfg=149 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi NERDTreeHelpCommand guifg=#fbec9f ctermfg=229 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi NERDTreeHelpTitle guifg=#4cc7e4 ctermfg=80 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi NERDTreeUp guifg=#9dd067 ctermfg=149 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi NERDTreeCWD guifg=#5ca7e4 ctermfg=74 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi NERDTreeOpenable guifg=#f05874 ctermfg=204 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi NERDTreeClosable guifg=#fbec9f ctermfg=229 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi pugJavascriptOutputChar guifg=#fbec9f ctermfg=229 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi pythonStatement guifg=#ecc48d ctermfg=222 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi pythonRepeat guifg=#ecc48d ctermfg=222 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi pythonFunction guifg=#54CED6 ctermfg=80 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi pythonExClass guifg=#DDCFBF ctermfg=187 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi pythonBuiltinObj guifg=#ecc48d ctermfg=222 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi pythonDot guifg=#FD9720 ctermfg=208 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi pythonBuiltinFunc guifg=#DDCFBF ctermfg=187 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi sqlStatement guifg=#54CED6 ctermfg=80 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi sqlKeyword guifg=#ffbe00 ctermfg=214 gui=bold cterm=bold")
vim.api.nvim_command("hi sqlSpecial guifg=#DC143C ctermfg=161 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi sqlType guifg=#6690c4 ctermfg=68 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi sqlFunction guifg=#ec5f67 ctermfg=203 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi mysqlKeyword guifg=#C33C4A ctermfg=131 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi mysqlOperator guifg=#2ba245 ctermfg=35 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi mysqlFunction guifg=#50c878 ctermfg=78 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi mysqlStatement guifg=#A1EFE4 ctermfg=158 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi mysqlType guifg=#0fb9e0 ctermfg=38 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi Quote guifg=#5f875f ctermfg=65 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi TSPunctBracket guifg=#54CED6 ctermfg=80 gui=bold cterm=bold")
vim.api.nvim_command("hi TSPunctSpectial guifg=#E7C547 ctermfg=185 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi TSField guifg=#9e71cf ctermfg=134 gui=bold cterm=bold")
vim.api.nvim_command("hi TSType guifg=#7d2c9d ctermfg=91 gui=bold cterm=bold")
vim.api.nvim_command("hi TSProperty guifg=#d7ffaf ctermfg=193 gui=bold cterm=bold")
vim.api.nvim_command("hi TSConstMacro guifg=#ff7273 ctermfg=203 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi TSParameter guifg=#66d9ef ctermfg=81 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi TSDefinition guifg=#88dfe9 ctermfg=116 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi TSConstructor guifg=#6690c4 ctermfg=68 gui=bold cterm=bold")
vim.api.nvim_command("hi TSFunctionBuiltin guifg=#A6E22D ctermfg=148 gui=bold cterm=bold")
vim.api.nvim_command("hi TSIdentifier guifg=#dacfb4 ctermfg=187 gui=bold cterm=bold")
vim.api.nvim_command("hi TSFuncBuiltin guifg=#ffbe00 ctermfg=214 gui=bold cterm=bold")
vim.api.nvim_command("hi TSTypeBuiltin guifg=#ffce51 ctermfg=221 gui=bold cterm=bold")
vim.api.nvim_command("hi typescriptParens guifg=#10aef8 ctermfg=39 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi typescriptLogicSymbols guifg=#f05874 ctermfg=204 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi typescriptReserved guifg=#3649dc ctermfg=62 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi typescriptLabel guifg=#1ABC9C ctermfg=37 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi typescriptFuncName guifg=#1aad16 ctermfg=34 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi typescriptCall guifg=#fbec9f ctermfg=229 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi typescriptVariable guifg=#3649dc ctermfg=62 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi typescriptBinaryOp guifg=#f05874 ctermfg=204 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi typescriptAssign guifg=#f05874 ctermfg=204 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi typescriptObjectLabel guifg=#10aef8 ctermfg=39 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi typescriptDotNotation guifg=#f05874 ctermfg=204 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi typescriptOperator guifg=#f05874 ctermfg=204 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi typescriptTernaryOp guifg=#f05874 ctermfg=204 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi typescriptTypeAnnotation guifg=#f05874 ctermfg=204 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi typescriptIdentifierName guifg=#dacfb4 ctermfg=187 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi typescriptArrowFuncArg guifg=#FD9720 ctermfg=208 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi typescriptParamImpl guifg=#fbec9f ctermfg=229 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi typescriptRepeat guifg=#9dd067 ctermfg=149 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi typescriptStatementKeyword guifg=#5ca7e4 ctermfg=74 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi typescriptAliasKeyword guifg=#9dd067 ctermfg=149 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi typescriptInterfaceKeyword guifg=#9ece6a ctermfg=149 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi typescriptTemplateSB guifg=#f05874 ctermfg=204 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi typescriptMemberOptionality guifg=#fbec9f ctermfg=229 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi typescriptOptionalMark guifg=#fbec9f ctermfg=229 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi typescriptUnaryOp guifg=#f05874 ctermfg=204 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi link typescriptBranch Statement")
vim.api.nvim_command("hi GitGutterAdd guifg=#9dd067 ctermfg=149 gui=NONE cterm=NONE")
vim.api.nvim_command("hi GitGutterChange guifg=#4cc7e4 ctermfg=80 gui=NONE cterm=NONE")
vim.api.nvim_command("hi GitGutterDelete guifg=#f05874 ctermfg=204 gui=NONE cterm=NONE")
vim.api.nvim_command("hi GitGutterChangeDelete guifg=#f05874 ctermfg=204 gui=NONE cterm=NONE")
vim.api.nvim_command("hi javaScriptOpSymbols guifg=#f05874 ctermfg=204 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi javaScriptParens guifg=#4cc7e4 ctermfg=80 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi javaScriptDocTags guifg=#A6E22D ctermfg=148 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi javaScriptDocSeeTag guifg=#6690c4 ctermfg=68 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi javaScriptBrowserObjects guifg=#5ca7e4 ctermfg=74 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi javaScriptDOMObjects guifg=#5ca7e4 ctermfg=74 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi javaScriptFuncArg guifg=#fbec9f ctermfg=229 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi jsParensIfElse guifg=#4cc7e4 ctermfg=80 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi jsObjectKey guifg=#4cc7e4 ctermfg=80 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi jsRepeat guifg=#9dd067 ctermfg=149 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi jsFunctionKey guifg=#9dd067 ctermfg=149 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi jsObjectFuncName guifg=#9dd067 ctermfg=149 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi jsNull guifg=#fbec9f ctermfg=229 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi jsObjectColon guifg=#f05874 ctermfg=204 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi jsParens guifg=#4cc7e4 ctermfg=80 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi jsFuncParens guifg=#4cc7e4 ctermfg=80 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi jsFuncArgs guifg=#fbec9f ctermfg=229 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi jsTemplateBraces guifg=#f05874 ctermfg=204 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi jsGlobalObjects guifg=#5ca7e4 ctermfg=74 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi jsExportDefaultGroup guifg=#5ca7e4 ctermfg=74 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi plug2 guifg=#9dd067 ctermfg=149 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi plugH2 guifg=#5ca7e4 ctermfg=74 guibg=NONE ctermbg=NONE gui=bold cterm=bold")
vim.api.nvim_command("hi plugBracket guifg=#4cc7e4 ctermfg=80 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi plugNumber guifg=#fbec9f ctermfg=229 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi plugDash guifg=#fbec9f ctermfg=229 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi plugStar guifg=#fbfcbf ctermfg=229 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi plugMessage guifg=#fbec9f ctermfg=229 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi plugName guifg=#4cc7e4 ctermfg=80 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi plugUpdate guifg=#f05874 ctermfg=204 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi plugEdge guifg=#9dd067 ctermfg=149 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi plugSha guifg=#fbfcbf ctermfg=229 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi plugNotLoaded guifg=#F92772 ctermfg=197 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi link SignifySignAdd GitGutterAdd")
vim.api.nvim_command("hi link SignifySignDelete GitGutterDelete")
vim.api.nvim_command("hi link SignifySignDeleteFirstLine SignifySignDelete")
vim.api.nvim_command("hi link SignifySignChange GitGutterChange")
vim.api.nvim_command("hi link SignifySignChangeDelete GitGutterChangeDelete")
vim.api.nvim_command("hi stylusVariable guifg=#dacfb4 ctermfg=187 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi stylusClass guifg=#9dd067 ctermfg=149 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi stylusClassChar guifg=#4cc7e4 ctermfg=80 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi stylusId guifg=#9dd067 ctermfg=149 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi stylusIdChar guifg=#4cc7e4 ctermfg=80 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi cssVisualVal guifg=#dacfb4 ctermfg=187 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi stylusImport guifg=#fbec9f ctermfg=229 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi vimCommentString guifg=#fbed7d ctermfg=228 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi vimCommentTitle guifg=#6690c4 ctermfg=68 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi vimError guifg=#dacfb4 ctermfg=187 guibg=#f05874 ctermbg=204 gui=NONE cterm=NONE")
vim.api.nvim_command("hi xmlNamespace guifg=#fbec9f ctermfg=229 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi xmlAttribPunct guifg=#f05874 ctermfg=204 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi xmlProcessingDelim guifg=#f05874 ctermfg=204 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi javascriptOpSymbol guifg=#f05874 ctermfg=204 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi javascriptDocNotation guifg=#A6E22D ctermfg=148 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi javascriptDocNamedParamType guifg=#6690c4 ctermfg=68 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi javascriptDocParamName guifg=#fbed7d ctermfg=228 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi javascriptDocParamType guifg=#6690c4 ctermfg=68 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi javascriptTemplateSB guifg=#f05874 ctermfg=204 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi javascriptRepeat guifg=#9dd067 ctermfg=149 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi javascriptObjectLabelColon guifg=#f05874 ctermfg=204 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi javascriptObjectMethodName guifg=#9dd067 ctermfg=149 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi javascriptFuncName guifg=#9dd067 ctermfg=149 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi yamlFlowString guifg=#fbfcbf ctermfg=229 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi yamlFlowStringDelimiter guifg=#dacfb4 ctermfg=187 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
vim.api.nvim_command("hi yamlKeyValueDelimiter guifg=#f05874 ctermfg=204 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE")
